### ISSUE TITLE
[1.18.2] DT Tectonic beta4 issue preventing world load

### ISSUE THREAD

**Issue by GrandmaPork** [DynamicTreesTeam/DynamicTrees-Tectonic#1]
![2023-05-06_13 24 08](https://user-images.githubusercontent.com/109642282/236639030-ac7ccaa3-f2f5-4a59-8899-f90cdede55c3.png)

**Comment by djsimmonds** [comment]
thanks for posting. i have uploaded a new version (beta5) which now sets the terratonic fix default to off, and also the config fixes now load automatically, so should work with modded servers. let me know if there are still issues with this new version

**Comment by Amber9572** [comment]
I'm having the same issue, with beta 5. I've checked my other mods, so I know its this one
